[package]
name = "bad-moon"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
ndarray = "0.16.1"
ordered-float = "4.6.0"
rodio = "0.20.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
video-rs = { version = "0.10.3", features = ["ndarray"] }
